# Sozvon/sozvon-client/Dockerfile.dev

FROM node:24-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json package-lock.json* yarn.lock* ./
RUN npm ci

# Копируем исходники
COPY . .

# Запускаем dev-сервер Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

EXPOSE 3000