# Sozvon/sozvon-client/Dockerfile.dev

FROM node:26-alpine3.24

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json ./
RUN npm install

# Копируем исходники
COPY . .

# Запускаем dev-сервер Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

EXPOSE 3000