import React from "react";

export const s: Record<string, React.CSSProperties> = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: 12,
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 12,
    borderBottom: "1px solid #e5e7eb",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  headerIcon: { fontSize: 28 },
  headerTitle: { fontWeight: 700, fontSize: 18, color: "#111827" },
  headerSub: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  createBtn: {
    padding: "7px 14px",
    background: "#111827",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    transition: "opacity 0.15s",
  },
  createRow: {
    display: "flex",
    gap: 8,
  },
  input: {
    flex: 1,
    padding: "8px 12px",
    border: "1.5px solid #e5e7eb",
    borderRadius: 8,
    fontSize: 14,
    outline: "none",
    fontFamily: "inherit",
  },
  errorBanner: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#dc2626",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  errorClose: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#dc2626",
    fontSize: 14,
  },
  callBar: {
    background: "#111827",
    color: "#fff",
    borderRadius: 10,
    padding: "10px 16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  callBarLeft: { display: "flex", alignItems: "center", gap: 10 },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
    flexShrink: 0,
  },
  callBarText: { fontSize: 13, color: "#d1d5db" },
  callBarRoom: { fontSize: 13, fontWeight: 700, color: "#fff" },
  callBarActions: { display: "flex", gap: 8 },
  callActionBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: 7,
    color: "#fff",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  roomsList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    overflowY: "auto",
    flex: 1,
  },
  empty: {
    color: "#9ca3af",
    fontSize: 14,
    textAlign: "center",
    paddingTop: 32,
  },
  roomCard: {
    background: "#fff",
    border: "1.5px solid #e5e7eb",
    borderRadius: 12,
    padding: "14px 16px",
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  roomCardActive: {
    borderColor: "#6366f1",
    boxShadow: "0 0 0 3px rgba(99,102,241,0.1)",
  },
  roomCardTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  roomInfo: { display: "flex", alignItems: "center", gap: 12 },
  roomIcon: { fontSize: 22 },
  roomName: { fontWeight: 600, fontSize: 15, color: "#111827" },
  roomMeta: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  roomActions: { display: "flex", alignItems: "center", gap: 6 },
  joinBtn: {
    padding: "6px 16px",
    background: "#6366f1",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  leaveBtn: {
    padding: "6px 16px",
    background: "#f3f4f6",
    color: "#374151",
    border: "none",
    borderRadius: 7,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  deleteBtn: {
    width: 28,
    height: 28,
    background: "none",
    border: "1px solid #e5e7eb",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    color: "#9ca3af",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  peersList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
    paddingTop: 10,
    borderTop: "1px solid #f3f4f6",
  },
  peerBadge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: 20,
    padding: "4px 10px 4px 4px",
  },
  peerAvatar: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "#e0e7ff",
    color: "#4338ca",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  },
  peerAvatarLive: {
    background: "#d1fae5",
    color: "#065f46",
  },
  peerName: { fontSize: 13, color: "#374151", fontWeight: 500 },
};
