# Sozvon\nginx\nginx.conf

user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {

	client_max_body_size 60m;

    upstream gateway {
        server gateway:8080;
    }

    upstream client {
        server client:3000;
    }

server {
    listen 443 ssl;
    server_name zvonya.ru www.zvonya.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Всё API и WS → Gateway
    location /api/ {
        proxy_pass         http://gateway/api/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_set_header   Host              $host;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Real-IP         $remote_addr;
    }

    location /ws {
        proxy_pass         http://gateway/ws;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_read_timeout 3600s;
    }

    # SPA
    location / {
        proxy_pass         http://client/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
    }
}
}